Cars refactoring
coders-school/Cars pull request #32
Opened 2020-09-22 13:43 UTC by McKucia

- Unique pointer instead of raw pointer engine.
- Engine cannot be changed when currentSpeed is different than zero.
- Exceptions: GearException and SpeedException
- Some Getters & Setters
- Encapsulations
- Speed cannot be set to negavite number.
- Tests (Hybrid, Petrol, Electric)

2020-09-22 15:31 UTC, MaciejSalamonski approved these changes

2020-09-22 15:31 UTC, MaciejSalamonski commented on Car.cpp
> +    currentSpeed_ = 0;
Maybe let's make these variables as constexpr variables

2020-09-23 06:01 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-09-23 06:01 UTC, WBigaj commented on PetrolEngine.cpp
> +    if(abs(gear - currentGear_) > 2) {
I suggest changing magic '2' to const variable. It would be easier to change program if changing gears rules would be changed.

2020-11-02 12:11 UTC, ziobron requested changes
Please add tests and set CI. Probably you forgot to commit one file.

2020-11-02 12:11 UTC, ziobron commented on ElectricCar.hpp
> +    std::unique_ptr<ElectricEngine> engine_;
should be private

2020-11-02 12:11 UTC, ziobron commented on GearException.cpp
> +}
There is no need to override this function. It's exactly the same behavior as in std::exception.

2020-11-02 12:11 UTC, ziobron commented on PetrolCar.hpp
> +    std::unique_ptr<PetrolEngine> engine_;
should be private

2020-11-02 12:11 UTC, ziobron commented on SpeedException.cpp
> +#include "SpeedException.hpp"
I don't see SpeedException.hpp commited in this repo.

2020-11-18 10:22 UTC, closed without merging